include:
  - ./api/compose.yaml
services:
  stripe:
    image: stripe/stripe-mock
    restart: always
    container_name: fake-stripe
    ports:
      - 12111:12111
      - 12112:12112
  client:
    container_name: client
    build:
      context: client
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - gcs
      - api
      - stripe
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: ./client
