services:
  gcs:
    image: fsouza/fake-gcs-server
    restart: always
    container_name: fake-gcs
    environment:
      FAKE_GCS_SCHEME: http
    ports:
      - 4443:4443
    volumes:
      - ./assets:/data
  mongo:
    image: mongo:8.2.7
    # platform: windows/amd64
    restart: always
    container_name: mongo
    command: mongod --port 27018
    ports:
      - 27018:27018
  api:
    container_name: singles-api
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 8080:8080
    links:
      - gcs
      - mongo
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: ./api
