services:
  gcs:
    image: fsouza/fake-gcs-server
    restart: always
    container_name: fake-gcs
    environment:
      FAKE_GCS_SCHEME: http
    ports:
      - 4443:4443
    volumes:
      - ./assets:/data
  api:
    container_name: singles-api
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 8080:8080
    links:
      - gcs
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: ./api
